# Generated by Django 5.1.6 on 2025-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear_tune', '0002_gamesession_user_alter_challenge_challenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
