# Generated by Django 5.1.6 on 2025-03-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear_tune', '0004_gamesession_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='attempts_left',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ear_tune.gamesession'),
        ),
    ]
