# Generated by Django 5.1.6 on 2025-05-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear_tune', '0005_gamesession_attempts_left_gamesession_is_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_frequency', models.IntegerField()),
                ('max_frequency', models.IntegerField()),
                ('center_frequency', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EQChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_audio', models.CharField(max_length=200)),
                ('change_amount', models.IntegerField(choices=[(-12, '-12 dB'), (-9, '-9 dB'), (-6, '-6 dB'), (-3, '-3 dB'), (0, 'No Change'), (3, '+3 dB'), (6, '+6 dB'), (9, '+9 dB'), (12, '+12 dB')])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('hint_text', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_challenges', to='ear_tune.game')),
                ('frequency_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ear_tune.frequencyband')),
            ],
        ),
    ]
