# Generated by Django 5.1.6 on 2026-02-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear_tune', '0006_frequencyband_eqchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhythmChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_data', models.JSONField()),
                ('tempo', models.IntegerField(default=120)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('audio_file', models.CharField(max_length=200)),
                ('correct_pattern', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhythm_challenges', to='ear_tune.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
